# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  UnitTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Install modules
        run: pnpm install
      - name: Run Test
        run: cd packages/smarty-ui-vite && pnpm run test:run
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.1.0
        with:
          node-version: 16
      - name: Install modules
        run: pnpm install
      - name: Run Vuild
        run: cd packages/smarty-ui-vite && pnpm run build
      - name: Run Test
        run: cd packages/smarty-ui-vite && pnpm run test
